version: '3'
name: nginx_certbot
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - nginx-proxy

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    hostname: certbot
    profiles:
      - sslcertificates
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
